services:
  server:
    container_name: media_manager_server
    image: media_manager_server:1.0.0
    depends_on:
      - database
      - redis
    env_file:
      - .env
    networks:
      - media_manager_network
    build:
      context: .
      dockerfile: ./Dockerfile.development
      target: development
    command: npm run start:${NPM_START_SCRIPT_SUFFIX:-dev}
    volumes:
      - .:/usr/src/app
      - ${MEDIA_UPLOAD_PATH}:/usr/src/app/upload
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${DEBUG_PORT:-9229}:${DEBUG_PORT:-9229}
  database:
    container_name: ${DATABASE_HOST}
    image: postgres:16.1
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    networks:
      - media_manager_network
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
  redis:
    container_name: media_manager_redis
    image: redis:7.2.4
    networks:
      - media_manager_network
  nginx:
    container_name: media_manager_nginx
    image: nginx:stable
    depends_on:
      - server
    env_file:
      - .env
    networks:
      - media_manager_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${NGINX_HOST_PORT_1}:${NGINX_CONTAINER_PORT_1}
      - ${NGINX_HOST_PORT_2}:${NGINX_CONTAINER_PORT_2}
    logging:
      driver: none

networks:
  media_manager_network:
    driver: bridge
volumes:
  uploaded_medias: {}
  database_data: {}
