name: main

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  main_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Media Manager Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.development
          platforms: linux/amd64, linux/arm64
          pull: true
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/media-manager:latest
            ${{ secrets.DOCKER_USERNAME }}/media-manager:latest-arm64
